version: '3'
services:
  mongodb:
    image: mongo
    restart: always
    networks:
      - mongodb

  nestjs-api:
    image: nest-cloud-run
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    networks:
      - mongodb
    environment:
      MONGO_URL: mongodb://mongodb:27017/testProject
networks:
  mongodb:
    driver: bridge
